#!/bin/sh
#/---
#Created by:  Scraft161
#Function:    initialize Discord with my preferred client mods
#Usage:       initcord
#Description: cleans discord install, and installs openasar and kernel.
#---/

# Create remporary download directory and download required assets
mkdir "$HOME/discord-install-tmp"

printf '%s\n' "[Info]: Downloading assets, we will start the installation after, so stand by"

wget -O $HOME/discord-install-tmp/app.asar https://github.com/GooseMod/OpenAsar/releases/download/nightly/app.asar
wget -O $HOME/discord-install-tmp/kernel-installer-x86_64-linux https://github.com/kernel-mod/installer-cli/releases/download/refs%2Fheads%2Fmaster/kernel-installer-x86_64-linux
wget -O $HOME/discord-install-tmp/kernel.asar https://github.com/kernel-mod/electron/releases/download/2021-11-26-21-53-07/kernel.asar

# Remove discord installation files to make sure we are dealing with a fresh install.
sudo rm -rf /opt/discord
sudo pacman -S discord

# Install OpenAsar
sudo mv /opt/discord/resources/app.asar /opt/discord/resources/app.asar.bak
sudo mv $HOME/discord-install-tmp/app.asar /opt/discord/app.asar

# Create required directories and symlink properly
sudo mkdir /etc/kernel-mod
sudo chmod 777 /etc/kernel-mod
ln -s /etc/kernel-mod $HOME/kernel-mod

# install kernel
sudo mv $HOME/discord-install-tmp/kernel.asar /etc/kernel-mod/kernel.asar
sudo $HOME/discord-install-tmp/kernel-installer-x86_64-linux -i /opt/discord -k /etc/kernel-mod
rm $HOME/discord-install-tmp/kernel-installer-x86_64-linux

# remove installation files
rm $HOME/discord-install-tmp/*
rmdir $HOME/discord-install-tmp
